# -*- coding: utf-8 -*-
"""prog3-12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZw-wJPN5y-ohRVEcai0Jx6tE_wAXKAL
"""

from google.colab import files
files.upload() # kaggle.jsonをアップロード
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

from sklearn.impute import SimpleImputer
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier \
as RandomForest
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
# KNNImputerクラスをインポート
from sklearn.impute import KNNImputer

# データの準備
def prepare():
    !kaggle datasets download -d uciml/horse-colic
    !unzip horse-colic.zip

# データを読込み
def preprocess():
    df_train = pd.read_csv('horse.csv')
    df_train = df_train.replace('NA', 'NaN')
    # 分類に使用する特徴量
    features = [ 'surgery', 'age', 
                 'rectal_temp', 'pulse',
                 'respiratory_rate', 
                 'packed_cell_volume',
                 'total_protein', 
                 'abdomo_protein',
                 'surgical_lesion',
                 'lesion_1', 'lesion_2', 'lesion_3','cp_data']
    print(len(df_train))
    X = df_train.loc[:,features].values
    y = df_train.loc[:,['outcome']].values
    return df_train, X, y, features

# KNNImputerによる補完
def replace_knn(df_train, features, imp):
    # outcomeを0,1,2（died/euthanized/lived) に置換 
    mp = {'died':0, 'euthanized':1, 'lived':2}
    kys = list(mp.keys())
    df_train = df_train[df_train['outcome'].isin(kys)]
    yesno = {'no':0, 'yes':1}
    # surgery, surgical_lesion, cp_data の
    # 列の値を0,1（no/yes) に置換
    for f in ['surgery', 'surgical_lesion', 'cp_data']:
        df_train[f].replace(yesno, inplace=True)
    # ageを0,1（young/adult) に置換
    df_train['age'].replace({'young': 0, 'adult': 1},
                            inplace=True)
    # 分類に使用するデータを格納
    X_train = df_train.loc[:, features].values
    # outcomeラベルをターゲットに格納
    df_y = pd.DataFrame(df_train.loc[:,['outcome']].values,
   columns=['outcome'])
    y_train = df_y.replace(mp).values.ravel()
    # データフレームに格納して、
    # 欠損値が無くなっていることを確認
    df = pd.DataFrame(X_train, columns=features)
    print('# of Missing Values:\n', 
          df.isnull().any(axis=1).value_counts())
    if imp == None:
        # n_neighbors: 補完の際に使用する近傍のサンプル数
        imp = KNNImputer(n_neighbors=3) 
    imp.fit(X_train)
    X_train = imp.transform(X_train)
    return X_train, y_train, imp

def main():
    prepare() 
    df_train, X, y, features = preprocess()
    # 学習データとテストデータに分ける(train:test = 7:3)
    X_train, X_test, y_train, y_test = train_test_split(
                                      X, y, 
                                      train_size=0.7, 
                                      random_state=1)
    fc = features + ['outcome']
    df_train = pd.DataFrame(np.concatenate(
                           (X_train,y_train),
   axis=1), columns=fc)
    X_train, y_train, imp = replace_knn(
                            df_train, features, None)
    fc = features + ['outcome']
    df_test = pd.DataFrame(np.concatenate(
                           (X_test, y_test),
                            axis=1), columns=fc) 
    
    X_test, y_test, _ = replace_knn(
                        df_test, features, imp) 
    model = RandomForest(n_estimators=100, random_state=1,
                        max_depth=7).fit(X_train, y_train)
    print('Accuracy: {:.3f}'.format(model.score(X_test,
                                    y_test)))
    y_pred = model.predict(X_test)
    target_names = ['died', 'euthanized', 'lived']
    print(classification_report(y_test, y_pred,
                                target_names=target_names))

if __name__ == '__main__':
    main()