# -*- coding: utf-8 -*-
"""prog3-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0qrXlRYamxth5JTKgy8Rtu5kMXesyVw
"""

from google.colab import files
files.upload() # kaggle.jsonをアップロード
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

# データの準備（Kaggle API を用いたデータのダウンロード）
!kaggle datasets download -d \
sgonkaggle/youtube-trend-with-subscriber
!unzip youtube-trend-with-subscriber.zip

import pandas as pd
# 標準化のためのscipy.statsをインポート
import scipy.stats as stats
# データのダウンロードについてはプログラム3.1と同じなので省略
# CSVファイルを読み込んでデータフレームに格納
df = pd.read_csv('USvideos_modified.csv')
df = df.loc[:,['views', 'likes', 'dislikes', 'comment_count']]
# データフレームに格納されている内容をzscoreで標準化
score = stats.zscore(df)
print(score)